name: Firebase Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: start
        run: echo start of script...
      - uses: lowply/deploy-firebase@v0.0.2 
      - name: Deploy to Firebase
        run: |
          echo Deploying to firebase...
          firebase deploy --token ${{FIREBASE_TOKEN}}
