name: Firebase Deploy

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Testing Workflow
      - uses: w9jds/firebase-action@master
      - run: |
          echo Deploying to firebase... && pwd && whoami && ls -la
          ls -la ..
      - name: Deploy to Firebase
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
