name: Firebase Deploy

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test --watchAll=false
      - name: Build
        run: yarn build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Deploy to Firebase
        run: npx firebase-tools@13 deploy -P live --only hosting:jordanportfoliosite
