name: Firebase Deploy

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Testing Workflow
        run: |
          echo testing action && pwd && whoami && ls
          ls -la
          ls -la ..
          ls -la ../../
          ls -la ../../../
      - name: Echo step
        run: |
          echo Deploying to firebase...
      - name: Install Firebase
        run: npm install firebase-tools
      - name: deploy
        run: firebase deploy --only hosting --token ${{secrets.FIREBASE_TOKEN}}
