name: Firebase Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: lowply/deploy-firebase@v0.0.2 
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Deploy to Firebase
      run: |
        echo Deploying to firebase...
        firebase deploy --token ${{FIREBASE_TOKEN}}
